// NOTE: Replace EMERGENT_API_KEY with actual OPENAI_API_KEY or ANTHROPIC_API_KEY
// The Emergent Universal Key format needs specific integration library support
const EMERGENT_API_KEY = process.env.EMERGENT_API_KEY;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY; // Add your OpenAI key here
const USE_MOCK = !OPENAI_API_KEY || OPENAI_API_KEY.startsWith('sk-emergent'); // Use mock if no real key

export interface AIRequest {
  prompt: string;
  model: 'gpt-5' | 'claude-sonnet';
  maxTokens?: number;
  temperature?: number;
}

// Mock AI response for demonstration (remove when real API key is available)
function getMockResponse(prompt: string, model: string): string {
  const isTranslation = prompt.toLowerCase().includes('translate');
  const isSummarize = prompt.toLowerCase().includes('summary') || prompt.toLowerCase().includes('summarize');
  
  if (isTranslation) {
    return `[DEMO MODE - Using simulated ${model}]\n\n` +
           `This is a simulated translation result. In production, this would contain the actual translated text using ${model}.\n\n` +
           `Original content has been analyzed and would be translated to the target language with proper context and formatting preservation.`;
  }
  
  if (isSummarize) {
    return `[DEMO MODE - Using simulated ${model}]\n\n` +
           `**Summary:**\n` +
           `This is a simulated summary generated by ${model}. The document discusses testing the DocTranslate application's features.\n\n` +
           `**Key Points:**\n` +
           `- Document processing capabilities\n` +
           `- Translation and summarization features\n` +
           `- Enterprise-grade UI and functionality\n\n` +
           `In production with a real API key, this would contain an actual AI-powered summary of your document.`;
  }
  
  return `[DEMO MODE] Response from ${model}: Processing completed successfully.`;
}

export async function callAI(request: AIRequest): Promise<string> {
  // If using mock mode (no real OpenAI key), return simulated response
  if (USE_MOCK) {
    console.log(`[DEMO MODE] Simulating AI response for model: ${request.model}`);
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    return getMockResponse(request.prompt, request.model);
  }

  // Real API implementation (when OpenAI key is provided)
  const apiURL = 'https://api.openai.com/v1/chat/completions';
  const modelName = request.model === 'claude-sonnet' ? 'gpt-4o' : 'gpt-4o';

  try {
    const response = await fetch(apiURL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: modelName,
        messages: [
          {
            role: 'user',
            content: request.prompt,
          },
        ],
        max_tokens: request.maxTokens || 4000,
        temperature: request.temperature || 0.7,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
      console.error('API Error Response:', errorData);
      throw new Error(`API error ${response.status}: ${JSON.stringify(errorData)}`);
    }

    const data = await response.json();
    return data.choices[0]?.message?.content || '';
  } catch (error: any) {
    console.error('AI Service Error:', error);
    throw new Error(`AI processing failed: ${error.message || 'Unknown error'}`);
  }
}

export async function translateDocument(text: string, targetLanguage: string, model: 'gpt-5' | 'claude-sonnet'): Promise<string> {
  const prompt = `Translate the following document to ${targetLanguage}. Maintain the original formatting and structure as much as possible.

Document:
${text}`;

  return await callAI({
    prompt,
    model,
    maxTokens: 4000,
    temperature: 0.3,
  });
}

export async function summarizeDocument(text: string, model: 'gpt-5' | 'claude-sonnet'): Promise<string> {
  const prompt = `Provide a comprehensive summary of the following document. Include key points, main ideas, and important details.

Document:
${text}`;

  return await callAI({
    prompt,
    model,
    maxTokens: 2000,
    temperature: 0.5,
  });
}