// NOTE: Replace EMERGENT_API_KEY with actual OPENAI_API_KEY or ANTHROPIC_API_KEY
// The Emergent Universal Key format needs specific integration library support
const EMERGENT_API_KEY = process.env.EMERGENT_API_KEY;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY; // Add your OpenAI key here
const USE_MOCK = !OPENAI_API_KEY || OPENAI_API_KEY.startsWith('sk-emergent'); // Use mock if no real key

export interface AIRequest {
  prompt: string;
  model: 'gpt-5' | 'claude-sonnet' | 'gpt-4o';
  maxTokens?: number;
  temperature?: number;
  jsonMode?: boolean; // Request JSON response
  imageUrl?: string; // For Vision/OCR
}

export interface TranslationResult {
  translated_text: string;
  review_points: {
    original: string;
    translation: string;
    confidence: number; // 0-1
    alternatives: string[];
    reason: string;
  }[];
}

// Mock AI response for demonstration (remove when real API key is available)
function getMockResponse(prompt: string, model: string, jsonMode?: boolean): string {
  if (jsonMode) {
    return JSON.stringify({
      translated_text: "[DEMO MODE] This is a simulated translation result. In production, this would contain the actual translated text.",
      review_points: [
        {
          original: "Demo term",
          translation: "Simulated term",
          confidence: 0.85,
          alternatives: ["Test term", "Example term"],
          reason: "Context suggests this is a demonstration."
        }
      ]
    });
  }

  const isTranslation = prompt.toLowerCase().includes('translate');
  const isSummarize = prompt.toLowerCase().includes('summary') || prompt.toLowerCase().includes('summarize');

  if (isTranslation) {
    return `[DEMO MODE - Using simulated ${model}]\n\n` +
      `Original content has been analyzed and would be translated into the target language with proper context and formatting preservation.`;
  }

  if (isSummarize) {
    return `[DEMO MODE - Using simulated ${model}]\n\n` +
      `**Summary:**\n` +
      `This is a simulated summary generated by ${model}. The document discusses testing the DocTranslate application's features.\n\n` +
      `**Key Points:**\n` +
      `- Document processing capabilities\n` +
      `- Translation and summarization features\n` +
      `- Enterprise-grade UI and functionality\n\n` +
      `In production with a real API key, this would contain an actual AI-powered summary of your document.`;
  }

  return `[DEMO MODE] Response from ${model}: Processing completed successfully.`;
}

export async function callAI(request: AIRequest): Promise<string> {
  // If using mock mode (no real OpenAI key), return simulated response
  if (USE_MOCK) {
    console.log(`[DEMO MODE] Simulating AI response for model: ${request.model}`);
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    return getMockResponse(request.prompt, request.model, request.jsonMode);
  }

  // Real API implementation (when OpenAI key is provided)
  const apiURL = 'https://api.openai.com/v1/chat/completions';

  // Map "gpt-5" to the best available model for now, or use as is if API supports it later
  let modelName = request.model === 'claude-sonnet' ? 'gpt-4o' : 'gpt-4o';
  if (request.model === 'gpt-5') {
    // Placeholder: "gpt-5" maps to "gpt-4o" until officially released/available
    modelName = 'gpt-4o';
  }

  try {
    const messages: any[] = [{ role: 'user', content: request.prompt }];

    // Handle Vision/Image input
    if (request.imageUrl) {
      messages[0].content = [
        { type: "text", text: request.prompt },
        { type: "image_url", image_url: { url: request.imageUrl } }
      ];
    }

    const payload: any = {
      model: modelName,
      messages: messages,
      max_tokens: request.maxTokens || 4000,
      temperature: request.temperature || 0.7,
    };

    if (request.jsonMode) {
      payload.response_format = { type: "json_object" };
    }

    const response = await fetch(apiURL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OPENAI_API_KEY}`,
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
      console.error('API Error Response:', errorData);
      throw new Error(`API error ${response.status}: ${JSON.stringify(errorData)}`);
    }

    const data = await response.json();
    return data.choices[0]?.message?.content || '';
  } catch (error: any) {
    console.error('AI Service Error:', error);
    throw new Error(`AI processing failed: ${error.message || 'Unknown error'}`);
  }
}

export async function translateDocument(
  text: string,
  targetLanguage: string,
  model: 'gpt-5' | 'claude-sonnet',
  glossaryContext?: string
): Promise<TranslationResult> {

  let prompt = `You are a professional translator. Translate the following document to ${targetLanguage}.
  
IMPORTANT: Return the result strictly as a valid JSON object with the following structure:
{
  "translated_text": "The full translated document text here, maintaining original formatting.",
  "review_points": [
      {
          "original": "source term",
          "translation": "translated term",
          "confidence": 0.8,
          "alternatives": ["alt 1", "alt 2"],
          "reason": "Explain why this term was chosen or flagged."
      }
  ]
}
Identify ambiguous terms, jargon, or low-confidence translations and include them in "review_points".
`;

  if (glossaryContext) {
    prompt += `\n\nUse the following Glossary for specific term translations:\n${glossaryContext}\n\n`;
  }

  prompt += `\nDocument Content:\n${text}`;

  const responseJson = await callAI({
    prompt,
    model,
    maxTokens: 4000,
    temperature: 0.3,
    jsonMode: true
  });

  try {
    return JSON.parse(responseJson) as TranslationResult;
  } catch (e) {
    console.error("Failed to parse AI JSON response", e);
    // Fallback if JSON parsing fails
    return {
      translated_text: responseJson,
      review_points: []
    };
  }
}

export async function summarizeDocument(text: string, model: 'gpt-5' | 'claude-sonnet'): Promise<string> {
  const prompt = `Provide a comprehensive summary of the following document. Include key points, main ideas, and important details.
Document:
${text}`;

  return await callAI({
    prompt,
    model,
    maxTokens: 2000,
    temperature: 0.5,
  });
}

export async function editDocument(text: string, instruction: string, model: 'gpt-5' | 'claude-sonnet'): Promise<string> {
  const prompt = `You are an expert editor. Modify the following document according to the user's instructions. Maintain the original structure unless asked to change it.
    
Instructions: ${instruction}

Document:
${text}`;

  return await callAI({
    prompt,
    model,
    maxTokens: 4000,
    temperature: 0.7
  });
}

export async function analyzeImage(base64Image: string, promptText: string = "Describe this image and extract any text found.", model: 'gpt-5' | 'claude-sonnet'): Promise<string> {
  // Ensure data URL format if not provided
  const imageUrl = base64Image.startsWith('data:') ? base64Image : `data:image/jpeg;base64,${base64Image}`;

  return await callAI({
    prompt: promptText,
    model,
    imageUrl: imageUrl,
    maxTokens: 2000,
    temperature: 0.5
  });
}
